/*
* My input key defines
*
* @author: Kai Yang
*/

//VPAD BUTTON DEFINE
#define VPAD_BUTTON_UNKNOWN 0
#define VPAD_BUTTON_A 1
#define VPAD_BUTTON_B 2
#define VPAD_BUTTON_X 3
#define VPAD_BUTTON_Y 4
#define VPAD_BUTTON_START 5
#define VPAD_BUTTON_SELECT 6
#define VPAD_BUTTON_L1 7
#define VPAD_BUTTON_L2 8
#define VPAD_BUTTON_R1 9
#define VPAD_BUTTON_R2 10
#define VPAD_BUTTON_LEFT 11
#define VPAD_BUTTON_RIGHT 12
#define VPAD_BUTTON_UP 13
#define VPAD_BUTTON_DOWN 14
#define VPAD_BUTTON_MOUSE1 15
#define VPAD_BUTTON_MOUSE2 16
#define VPAD_BUTTON_MOUSE3 17
#define VPAD_BUTTON_MOUSE4 18
#define VPAD_BUTTON_MOUSE5 19
#define VPAD_BUTTON_MOUSE6 20
#define VPAD_BUTTON_MOUSE7 21
#define VPAD_BUTTON_MOUSE8 22
#define VPAD_BUTTON_10 23
#define VPAD_BUTTON_11 24
#define VPAD_BUTTON_12 25
#define VPAD_BUTTON_13 26
#define VPAD_BUTTON_14 27
#define VPAD_BUTTON_15 28
#define VPAD_BUTTON_16 29
//todo:all the keyboard keys


//VPADDATA AXIS DEFINE
#define VPAD_AXIS_LX 0
#define VPAD_AXIS_LY 1
#define VPAD_AXIS_RX 2
#define VPAD_AXIS_RY 3
#define VPAD_AXIS_LT 4
#define VPAD_AXIS_RT 5
#define VPAD_AXIS_6 6
#define VPAD_AXIS_7 7
#define VPAD_AXIS_8 8
#define VPAD_AXIS_9 9
#define VPAD_AXIS_10 10
#define VPAD_AXIS_11 11
#define VPAD_AXIS_12 12
#define VPAD_AXIS_13 13
#define VPAD_AXIS_14 14
#define VPAD_AXIS_15 15

//VPADDATA INT VALUE DEFINE
#define VPAD_INT_0 0
#define VPAD_INT_1 1
#define VPAD_INT_2 2
#define VPAD_INT_3 3
#define VPAD_INT_4 4
#define VPAD_INT_5 5
#define VPAD_INT_6 6
#define VPAD_INT_7 7